# Generated by Django 4.1.6 on 2023-04-09 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_scanner_monitor_computer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="floor",
            new_name="department",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="branch",
        ),
    ]
