# Generated by Django 4.1.6 on 2023-04-12 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0002_department_printer"),
        ("employees", "0004_alter_computer_invontorynumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eployees",
                to="branches.department",
            ),
        ),
    ]
