# Generated by Django 4.1.6 on 2023-04-12 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_alter_employee_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computer",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="computers",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monitors",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="scanner",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scanners",
                to="employees.employee",
            ),
        ),
    ]
