# Generated by Django 4.1.6 on 2023-04-15 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0002_department_printer"),
    ]

    operations = [
        migrations.AddField(
            model_name="branche",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="branches"),
        ),
        migrations.AlterField(
            model_name="department",
            name="floor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="branches.floor",
            ),
        ),
        migrations.AlterField(
            model_name="floor",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="floors",
                to="branches.branche",
            ),
        ),
    ]
